// Generated by sr_practice/data/build_bgm_table.py -- do not edit by hand.
// Which track a fight plays. The battle scene does not carry one; the EVENT that
// starts the fight does (event/schedule/ev_*/bin/*.xwb), and the arena name that
// startBattle_l reports joins the two: "bt_gapr_200_cb" <-> ev_gapr_200.
#ifndef FF13_BGM_TABLE_H
#define FF13_BGM_TABLE_H

// Zone id -> the boss track that zone's own events use. Boss themes differ by
// area, so this follows the area without anything having to be observed first.
typedef struct { unsigned short zone; const char* track; } ff13_bgm_zone;
static const ff13_bgm_zone kBgmZone[] = {
    {  2, "music_bossa"},
    {  3, "music_bossa"},
    {  4, "music_40monst_b"},
    {  6, "music_16gfaru_b"},
    {  8, "music_bossa"},
    { 15, "music_bossa"},
    { 16, "music_bossa"},
    { 17, "music_16gfaru_b"},
    { 18, "music_theme_b"},
    { 19, "music_bossa"},
    { 21, "music_16gfaru_b"},
    { 22, "music_28shouk_b"},
    { 26, "music_16gfaru_b"},
    { 27, "music_74faru1_b"},
    { 29, "music_106ofa2_b"},
};
#define FF13_BGM_ZONE_N ((int)(sizeof(kBgmZone)/sizeof(kBgmZone[0])))

// "<area>_<nnn>" (the arena name with its "bt_" prefix and "_cb" suffix removed)
// -> the exact track that fight plays.
typedef struct { const char* ev; const char* track; } ff13_bgm_event;
static const ff13_bgm_event kBgmEvent[] = {
    {"eden_020", "music_bossa"},
    {"eden_050", "music_28shouk_b"},
    {"eden_100", "music_bossa"},
    {"eden_220", "music_16gfaru_b"},
    {"fark_090", "music_40monst_b"},
    {"fark_120", "music_28shouk_b"},
    {"fark_140", "music_theme_b"},
    {"gapr_200", "music_bossa"},
    {"gpcg_050", "music_16gfaru_b"},
    {"gptt_030", "music_16gfaru_b"},
    {"gpwo_030", "music_74faru1_b"},
    {"gpyu_010", "music_28shouk_b"},
    {"hang_000", "music_bossa"},
    {"hgcr_100", "music_bossa"},
    {"hgcr_170", "music_bossa"},
    {"hgcr_180", "music_theme_b"},
    {"hgcr_195", "music_28shouk_b"},
    {"hgcr_905", "music_theme_b"},
    {"hgin_010", "music_theme_b"},
    {"hgin_290", "music_28shouk_b"},
    {"hgin_320", "music_16gfaru_b"},
    {"hiku_120", "music_bossa"},
    {"hiku_180", "music_bossa"},
    {"hiku_190", "music_40monst_b"},
    {"hiku_230", "music_74faru1_b"},
    {"lasd_300", "music_74faru1_b"},
    {"lasd_310", "music_102far3_b"},
    {"lasd_370", "music_106ofa2_b"},
    {"nati_090", "music_40monst_b"},
    {"nati_140", "music_16gfaru_b"},
    {"pmpm_070", "music_bossa"},
    {"pmpm_120", "music_40monst_b"},
    {"pmpm_200", "music_bossa"},
    {"pmpm_300", "music_bossa"},
    {"pmpm_400", "music_28shouk_b"},
    {"vpek_170", "music_40monst_b"},
    {"vpek_200", "music_159opn_b"},
    {"vpek_310", "music_40monst_b"},
};
#define FF13_BGM_EVENT_N ((int)(sizeof(kBgmEvent)/sizeof(kBgmEvent[0])))

// btsc -> the track that fight plays, resolved offline (see build_bgm_table.py):
// the scene's arena mapset names its area, and within that area the event that
// stages the scene's enemy is the one whose track this is. Fights left out are
// the ones whose area holds several battle tracks with nothing to tell them
// apart; those fall back per area at runtime, or to [battle_swap] bgm_map.
// origin: 0 = joined from the event that stages the fight.
//         1 = the fight starts out of a cutscene and keeps the music that was
//             already playing -- there is no second playBgm, so the track comes
//             from the event that stages it rather than from a battle track.
//         2 = read off the game on hardware. Beats both of the above.
typedef struct { unsigned short btsc; const char* track; unsigned char origin; }
        ff13_bgm_scene;
#define FF13_BGM_JOINED   0
#define FF13_BGM_INHERIT  1
#define FF13_BGM_VERIFIED 2
static const ff13_bgm_scene kBgmScene[] = {
    { 1001, "music_bossa", 0},
    { 1016, "music_bossa", 0},
    { 2001, "music_theme_b", 0},
    { 2011, "music_12snow_1", 2},
    { 2017, "music_16gfaru_b", 2},
    { 3013, "music_bossa", 0},
    { 3032, "music_bossa", 0},
    { 3038, "music_bossa", 0},
    { 4001, "music_white_e3", 2},
    { 4026, "music_40monst_b", 0},
    { 4027, "music_white_e3", 2},
    { 4036, "music_40monst_b", 2},
    { 4037, "music_159opn_b", 0},
    { 4052, "music_white_e3", 2},
    { 4053, "music_40monst_b", 0},
    { 5027, "music_44sazh_3b", 1},
    { 6046, "music_bossa", 0},
    { 7031, "music_bossa", 0},
    { 7037, "music_bossa", 0},
    { 7042, "music_28shouk_b", 0},
    { 7050, "music_bossa", 0},
    { 7058, "music_158opn1_i", 2},
    { 8001, "music_34comical", 2},
    { 8002, "music_34comical", 2},
    { 8003, "music_34comical", 2},
    { 8004, "music_34comical", 2},
    { 8005, "music_34comical", 2},
    { 8006, "music_34comical", 2},
    { 8007, "music_34comical", 2},
    { 8008, "music_40monst_b", 0},
    { 8009, "music_34comical", 2},
    { 8010, "music_34comical", 2},
    { 8011, "music_34comical", 2},
    { 8012, "music_16gfaru_b", 2},
    { 9001, "music_154syuge2", 2},
    { 9026, "music_158opn1_i", 2},
    { 9034, "music_158opn1_i", 2},
    { 9035, "music_158opn1_i", 2},
    { 9036, "music_158opn1_i", 2},
    { 9037, "music_158opn1_i", 2},
    { 9038, "music_158opn1_i", 2},
    { 9039, "music_158opn1_i", 2},
    { 9040, "music_158opn1_i", 2},
    { 9041, "music_bossa", 2},
    { 9042, "music_16gfaru_b", 2},
    { 9043, "music_158opn1_i", 2},
    { 9044, "music_158opn1_i", 2},
    { 9045, "music_158opn1_i", 2},
    { 9046, "music_158opn1_i", 2},
    { 9047, "music_158opn1_i", 2},
    { 9048, "music_158opn1_i", 2},
    { 9049, "music_158opn1_i", 2},
    { 9050, "music_154syuge2", 2},
    { 9051, "music_158opn1_i", 2},
    { 9052, "music_158opn1_i", 2},
    { 9053, "music_158opn1_i", 2},
    { 9054, "music_158opn1_i", 2},
    { 9055, "music_74faru1_b", 0},
    { 9056, "music_158opn1_i", 2},
    { 9057, "music_158opn1_i", 2},
    { 9058, "music_158opn1_i", 2},
    { 9059, "music_158opn1_i", 2},
    { 9060, "music_158opn1_i", 2},
    { 9061, "music_158opn1_i", 2},
    { 9062, "music_158opn1_i", 2},
    { 9063, "music_158opn1_i", 2},
    { 9064, "music_158opn1_i", 2},
    { 9065, "music_158opn1_i", 2},
    { 9066, "music_158opn1_i", 2},
    { 9067, "music_158opn1_i", 2},
    { 9068, "music_158opn1_i", 2},
    { 9069, "music_158opn1_i", 2},
    { 9070, "music_158opn1_i", 2},
    { 9071, "music_158opn1_i", 2},
    { 9072, "music_158opn1_i", 2},
    { 9073, "music_158opn1_i", 2},
    { 9074, "music_158opn1_i", 2},
    { 9075, "music_158opn1_i", 2},
    { 9076, "music_158opn1_i", 2},
    { 9077, "music_158opn1_i", 2},
    {10034, "music_91teiji_f", 2},
    {10038, "music_white_e3", 2},
    {10039, "music_40monst_b", 0},
    {10060, "music_28shouk_b", 2},
    {11100, "music_16gfaru_b", 0},
    {11406, "music_bossa", 2},
    {11412, "music_28shouk_b", 0},
    {11628, "music_16gfaru_b", 0},
    {11709, "music_74faru1_b", 0},
    {11830, "music_158opn1_i", 2},
    {12001, "music_97eden_pa", 2},
    {12008, "music_bossa", 0},
    {12014, "music_47ppm", 2},
    {12034, "music_97eden_pa", 1},
    {12042, "music_97eden_pa", 2},
    {12081, "music_40monst_b", 2},
    {12083, "music_40monst_b", 2},
    {12084, "music_40monst_b", 2},
    {12090, "music_74faru1_b", 2},
    {12091, "music_102far3_b", 2},
    {12092, "music_106ofa2_b", 2},
};
#define FF13_BGM_SCENE_N ((int)(sizeof(kBgmScene)/sizeof(kBgmScene[0])))

#endif
