/*
 * FF13-SpeedrunPractice — speedrun practice mod for FINAL FANTASY XIII (Steam).
 * Copyright (C) 2026 Akiyoshi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef SRP_INTERNAL_H
#define SRP_INTERNAL_H

#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <ctype.h>
#include "ff13_hook.h"
// Per-scene names, sort key and tag, generated by sr_practice/data/build_btsc_picker.py from
// sr_practice/data/btsc_picker.tsv. Not committed (the strings are the game's own text); without
// it every fight is drawn unnamed and in the built-in order.
#if defined(__has_include)
#  if __has_include("btsc_picker.h")
#    include "btsc_picker.h"
#    define FF13_HAVE_BTSC_NAMES 1
#  endif
#endif
// Sort key for a fight the TSV does not list: it sorts after every listed row, grouped by kind.
#define FF13_BTSC_ORDER_LAST 0xFFFFu
// Fallbacks so the picker code compiles and reads the same without btsc_picker.h.
#ifndef FF13_NAME_KIND_BOSS
#  define FF13_NAME_KIND_BOSS    1
#  define FF13_NAME_KIND_EVENT   2
#  define FF13_NAME_KIND_MISSION 3
#endif
#ifndef FF13_BTSC_NO_TEXT
#  define FF13_BTSC_NO_TEXT 0xFFFFFFFFu
#endif
// A binding is a virtual-key code with its modifier bits packed above it, so a binding still
// travels as the single UINT everything already passes around.
#define HK_CTRL   0x0100u
#define HK_SHIFT  0x0200u
#define HK_ALT    0x0400u
#define HK_MODS   0x0700u
#define hk_key(x)  ((UINT)((x) & 0xFFu))
#define hk_mods(x) ((UINT)((x) & HK_MODS))
// Hotkey poll period; the loop and hk_edge live in dllmain.c. Declared here because srp_save.c
// stores its timeouts as tick counts = milliseconds / this period.
#define HK_POLL_MS 80
int hk_edge(UINT b, int* was);

// ---- generated tables read by more than one TU ----
#include "ovl_text.h"
#include "bgm_table.h"
// Which enemy models a scene needs and which charaset holds them (build_charaset_table.py).
// An enemy whose model is not resident is built and then fails to activate.
#include "charaset_table.h"
// What each battle scene fields, extracted from the game's btsc*.wdb (build_btsc_table.py).
#include "btsc_table.h"

// ---- shared constants: RVAs, field offsets and sizes ----
#define KILL_OFF      0
#define KILL_ONEHIT   1
#define KILL_INSTANT  2               // instant-win AND one-hit-kill
#define MOD_DATA_DIR "ff13-mods"
// ---- combat-actor field offsets (from `this`) ----
#define OFF_HP        0x290   // current HP   (int32) -- the field the cave writes
#define OFF_MAXHP     0x6C8   // max HP       (int32, direct dword; no indirection)
#define OFF_GUARD324  0x324   // enemy guard  (int32) -- the cave's enemy gate (party=0 / enemy!=0)
#define OFF_DEFEATED  0x259   // byte; bit 0x02 = defeated
#define OFF_TEAM      0x24E   // byte; bit 0x04 = this actor is on the enemy side
#define OFF_LIFECYCLE 0x270   // dword of eight nibbles; bits 12-15 = lifecycle (1 alive / 3 dead)
#define OFF_ACTOR_NAME 0x1A40 // charaspec name, 16 bytes NUL-padded (read off the placement join)
// Read span bounds-checked before touching an actor.
#define ACTOR_SPAN    (OFF_MAXHP + 4)
// ---- BattleMain state: read only by the overlay, to hide field-only lines during a battle ----
#define RVA_BM_PTR   0x23FD208   // VA 0x27FD208: pointer to the BattleMain singleton (BM)
#define OFF_BM_STATE 0x44        // [BM+0x44] = battle state machine (0 = idle; != 0 = in battle)
#define RVA_SETATBSPEED  0x0F5220     // VA 0x4F5220
#define RVA_FRAMETICK 0x2AA480   // VA 0x6AA480: app-clock tick; ecx=singleton, [esp+4]=int* frameDeltaMs
#define RVA_SETTER 0x1B21C0    // VA 0x5B21C0 (setAiTerritoryState backend: cdecl setter(id, state))
#define RVA_WH_HOOK 0x7E029D
#define RVA_WH_CONT 0x7E02A3
#define RVA_WH_SKIP 0x7E02E0
#define SUPPRESS_PREFIX "gr_mon_"
#define RVA_STARTBATTLE 0x7E3DF0     // VA 0xBE3DF0 startBattle_l entry
#define RVA_TARGETHP_PTR 0x24337B4
#define OFF_TARGETHP     0xBEC
#define BGM_NAME_MAX  16
#define BGM_HOLD_MAX_MS     8000
#define OFF_TOUCHED_ID 0x14648                    // [fieldMgr+0x14648] = pending touched object id
#define RVA_ENCSCENE 0x75032D        // VA 0xB5032D `mov [ecx+0x354],eax`
#define RVA_GETBTSC 0x741640         // VA 0xB41640 getBattleScene(id, flag), ecx = DataBattle DB
#define RVA_ENCID   0x7500A0         // VA 0xB500A0 (id) -> 0xB50270 on [0x282B190]
#define RVA_LOADSND 0x7DE1C0         // VA 0xBDE1C0 Resource.loadSoundResource(String, String)
#define RVA_LOADCHARASET 0x7DE930    // VA 0xBDE930 Resource.loadCharaByCharaSet(String)
#define CSET_NAME_MAX 39
#define RVA_LOADCHARA 0x7DED30       // VA 0xBDED30 Resource.loadChara(String)
#define RVA_ISLOADEDCHARA 0x7DEF80   // VA 0xBDEF80 Resource.isLoadedChara(String)
#define RVA_LOADBG 0x7DE6C0          // VA 0xBDE6C0 Resource.load_privBgByMapSet(String)
#define RVA_DRAWENV_BG    0x7E0EF0   // VA 0xBE0EF0  Scene.overwriteDrawEnvManually_l
#define RVA_DRAWENV_CHARA 0x7C9450   // VA 0xBC9450  Chara.setDrawEnvManually_l
#define RVA_BOX_ON  0x7DFF30         // VA 0xBDFF30  Scene.validateObject
#define RVA_BOX_OFF 0x7DFEC0         // VA 0xBDFEC0  Scene.invalidateObject
#define RVA_SCREENENV 0x7C4610       // VA 0xBC4610  Camera.enableAutoScreenEnv
#define RVA_LAYOUT_ON  0x7DFAC0      // VA 0xBDFAC0  Scene.showLayoutInstance (= sfShowBgInstance)
#define RVA_LAYOUT_OFF 0x7DFB40      // VA 0xBDFB40  Scene.hideLayoutInstance (= sfHideBgInstance)
#define RVA_OPTIMA_REGIST 0x7DCAF0   // VA 0xBDCAF0
#define RVA_OPTIMA_SET    0x7DCBC0   // VA 0xBDCBC0
#define RVA_OPTIMA_CLEAR  0x7DCC00   // VA 0xBDCC00
#define RVA_OPTIMA_CLRALL 0x7DCC50   // VA 0xBDCC50
#define RVA_ADDROLE       0x7DB910   // VA 0xBDB910
#define RVA_STARTCINEMA 0x7E33D0     // VA 0xBE33D0
#define EVENT_STAGE_MS 800
#define EVENT_GIVEUP_CAP_MS 20000
#define EVENT_SIDEEFFECT_MS 1200
#define ARENA_REACH 30.0f
#define ARENA_SAME  2.5f        // slots this close together ON THE GROUND are one character
#define ARENA_YBAND 5.0f
#define CHARA_NAME_OFF 0x4C
#define WARP_MAXSLOT 0x4000
#define OFF_BM_STAGE 0x3F4        // [BattleMain+0x3F4] = the 4x4 the battle places everything with
#define BOSS_SLOTS 12
#define ARENA_ENEMIES 6
#define BOSS_BUILD_MS 12000
#define ARENA_GATHER_MS 400
#define ARENA_SETTLE_MS 1500
#define ARENA_DERIVED_MS 6000
#define OPTIMA_LOG_MAX 400   // a story run to a fight can pass several party changes
#define LIGHT_MAP   1
#define LIGHT_CHARA 2
#define LIGHT_EASE_MS 1300
#define LIGHT_ROOM_AGAIN_MS 650
#define RVA_ISREAD_CALL 0x379642     // VA 0x779642  add ecx,0x182C
#define RVA_CSREQ 0x755160           // VA 0xB55160
#define RVA_ACTORSECT 0x3795EA       // VA 0x7795EA  add ecx,0xE8   (ecx = the actor)
#define RVA_STARTBTL 0x0BB5B0          // VA 0x4BB5B0 startBattle(btsc, flags)
#define RVA_GAMELOG 0x4A5B20              // VA 0x8A5B20
#define RVA_TRACE 0x4A5A60                 // VA 0x8A5A60
#define RVA_CAMSEQ 0x195620          // VA 0x595620
#define RVA_CAMREQ      0x0D6C20  // VA 0x4D6C20  __thiscall requestCamArts(BattleMain, req*, int)
#define RVA_HASCAM 0x7421A0                // VA 0xB421A0  __thiscall hasIntroCamera(wrapper)
#define RVA_FIELDMGR_PTR 0x23FF124     // VA 0x27FF124, candidate global
#define RVA_BGMPLAY   0x6CED90       // VA 0xACED90 BgmManager play entry (ecx, arg2 = name)
#define RVA_BGMLAZY   0x6CF080       // VA 0xACF080 BgmManager::lazyPlay (ecx, arg1 = name)
#define RVA_ENCCHECK   0x1CEE00       // VA 0x5CEE00 doEncountCheck (ecx = field manager)
#define BS_MENU_MAX 400   // the 11xxx band alone holds ~395 scenes
#define BS_NAME_COL 34
#define BS_ROWS 10
#define RVA_SPECREPL 0x71140         // VA 0x471140 -- the charaspec swap (thiscall)
#define RVA_ENCF4      0x7505B6        // VA 0xB505B6
#define RVA_RESOLVETGT 0x158E80      // VA 0x558E80
#define RVA_ABILLABEL 0x943B0        // VA 0x4943B0
#define RVA_AIAFTER   0x7C3300       // VA 0xBC3300 Battle.apiAiPushEnemyAfterExecArgs
// Refuse a warp home longer than this. The streaming budget measures ~390 units; a trip that
// overruns it strands the party on unstreamed ground, in a load the game never comes out of.
// 350 leaves margin on a figure that was measured rather than documented.
#define HOME_MAX_DIST 350.0f
#define RVA_SENDTRIG  0x417400            // VA 0x817400  __thiscall(ecx=ZSM, int trigger), ret 4
#define RVA_GOMENU         0x4ED130    // VA 0x8ED130 the game-over menu update
#define RVA_GOSE           0x4ED24D    // VA 0x8ED24D: the push/mov/call that makes the sound
#define GO_SE_LEN          13          // length of that sequence; all of it is blanked for silence
#define RVA_WORKER_HOW 0x414DDC      // VA 0x814DDC  mov eax, [0x27FF068] -- just after the store
#define RVA_WORKER_IN  0x414B90      // VA 0x814B90  push ebp; mov ebp,esp; sub esp,0x808
#define RVA_WORKER_ARM 0x414F6B      // VA 0x814F6B  push 0x10CEC80 -- both values are settled here
#define RVA_PLACEJOIN 0x66C07        // VA 0x466C07  mov eax, 2 -- the join, before the trace
#define RVA_ITEMTAKE  0x76A940      // VA 0xB6A940  __cdecl removeItem(const char id[16], int n)
#define RVA_ITEMCOUNT 0x7268E0      // VA 0xB268E0  __cdecl getItemCount(const char id[16]) -> int
#define RVA_ITEMGIVE  0x7268C0      // VA 0xB268C0  __cdecl addItem(const char id[16], int n, int f)
#define RVA_TPGET     0x7272E0      // VA 0xB272E0  __cdecl getTp(void) -> int
#define RVA_TPSET     0x7272F0      // VA 0xB272F0  __cdecl setTp(int)
#define RVA_LOCK_ENTER  0x11B50     // VA 0x00411B50  __thiscall(lock, int tag)  ret 4
#define RVA_LOCK_LEAVE  0x11BD0     // VA 0x00411BD0  __thiscall(lock)
#define RVA_LOADSHOW 0x4E2080      // VA 0x8E2080
#define RVA_LOADHIDE 0x4E2150      // VA 0x8E2150
#define RVA_ENCREFUSE 0x1CEEA4     // VA 0x5CEEA4
#define RVA_ACTIVATE      0x0DA820   // VA 0x004DA820  activateBattleChara entry (the probe)
#define RVA_ACTIVATE_GATE 0x0DA8A3   // VA 0x004DA8A3  cmp [ebp-0xb8],0 -- the residency verdict
#define RVA_GETWORLDPOS 0x38EEE0       // VA 0x78EEE0 GetWorldPos entry (ecx = SceneObject)
#define RVA_COMMIT      0x39C5E0       // VA 0x79C5E0 commit-transform (ecx=obj, arg0=Vector4* src)
#define RVA_CAM_RECENTER 0x236A20     // VA 0x636A20  __thiscall recenter(this)
#define RVA_WIDESHOT 0x1A5807     // VA 0x5A5807
#define RVA_GETCAM 0x2C0880       // VA 0x6C0880  void __cdecl getCurrentCamera(float out[16])
#define OVL_FLASH_OFF  0xFFA3A8A8   // status flash   : something switched off

// ---- shared types ----
typedef struct { const char* name; float x, y, z; } ff13_enemy;
typedef struct ff13_arena_s { uint16_t btsc; const char* arena; uint32_t flags;
                 float ex, ey, ez;      // the enemy, as an offset on the stage
                 float wp[3][3];        // the party, as three world positions
                 float bw[3];           // and the enemy's, for pointing them at it beforehand
                 float cm[16];          // the camera the story fight settles into, as a 4x4
                 float ct[3];           // what that camera looks at
                 float c0[3], ct0[3];   // the pair it opens on
                 float cd[3], cd2[3];   // the two that drag it in from wherever it was
                 float ca[2];           // and the angles it rests at once it gets there
                 float camHoldMs;       // how long to keep it there (0 = set it and let go)
                 int   restartAfterWin; // 1 = end a win at the checkpoint, 0 = let the story have it
                 const char* chset;     // character set to load first (NULL = the table's choice)
                 const char* bg;        // mapset holding the arena terrain (NULL = already there)
                 const char* bgm;       // NULL = resolve as usual; "" = keep the fight's own track
                                        // (the offline match is wrong for this scene)
                 float sp[3][3];        // where the SCENE stands the party (0 = kPartyStage)
                 ff13_enemy en[ARENA_ENEMIES];     // its enemies, when it fields more than one
                 const char* btlBg[2];             // the BATTLE's own mapsets (bt_scene cells 3/4)
                 const char* ev[4];                // event, callback, data pack, success label
                                                   // (NULL name = no event door; arena door instead).
                                                   // Also the source of the picker's "CS" mark: a
                                                   // door is the only way a picked fight plays a
                                                   // cutscene. See scene_has_cutscene.
                 const char* evChara[8];           // field characters its "before" function creates,
                                                   // as name/model pairs
                 const char* evArea[2];            // ...and the area groups it activates
                 const char* evPack2;              // a second data pack, where the story loads two
                 int evScript;                     // 1 = the entry point is a SCRIPT event rather
                                                   // than a cutscene (startCinema mode 0)
                 int evMarker;                     // party marker group to stand them on first
                                                   // (0 = none; the groups the game uses are 1-up)
                 float evPos[3];                   // ...or where to walk them, when the story
                                                   // relies on the player having walked there
                 const char* evLoad[2];            // cutscene + pack to load first, when the root
                                                   // is not itself the cutscene
                 int evFlag;                       // scenario flag to put back before firing, so a
                                                   // chain that has run can run again (0 = leave it)
                 int evMusic;                      // 1 = ask for this fight's own track anyway (an
                                                   // event door otherwise leaves music to the story)
                 const char* evSetup;              // script run once the chain is under way, for the
                                                   // one thing no native does: paradigms. Spent on
                                                   // the chain's next native call -- see g_setupWant
                 int evNoFight;                    // 1 = run the chain for its side effects, not the
                                                   // fight: evFlag is set rather than rewound (which
                                                   // shuts the trailing cutscene's gate) and the
                                                   // picker starts the fight itself afterwards
                 const char* evEvFlag;             // named event flag to raise before firing; the
                                                   // chains that check one mean "arrived at cold
                                                   // rather than walked into"
                 int evQuiet;                      // 1 = set the story's auto-music-off bit (Party
                                                   // work 1 bit 0) before firing, as the story's
                                                   // OWN staging does -- the battle step then rolls
                                                   // no theme and the chain's track carries through
                 int evGate;                       // scenario-flag value that SHUTS the chain's
                                                   // replay after a converted end (0 = none), or
                                                   // the reload re-fights instead of giving the
                                                   // field back
                 const char* evEndRp;              // restart point RE-MARKED at fight-over so a
                                                   // converted end reloads OUTSIDE a chain that
                                                   // marked its checkpoint inside itself (NULL =
                                                   // leave the checkpoint alone)
                 const char* evRpFlag;             // the event flag this fight's RESTART LOADER
                                                   // raises; taken down at the pick and after the
                                                   // way back, or the chain opens its preparation
                                                   // menu on every pick
                 int noHomeWarp; }                 // 1 = leave the party where the fight's own end
                                                   // puts them (the spot is still recorded). LAST
                                                   // on purpose: rows initialise positionally, so
                                                   // a field inserted above silently shifts them
        ff13_arena;

// ---- diagnostic probes (release builds get the no-ops) ----
#ifdef FF13_DIAG
void turn_watch_tick(void);
void boss_basis_probe(void);
void encinfo_probe(const char* when);
#else
#define turn_watch_tick() ((void)0)
#define boss_basis_probe() ((void)0)
#endif

// ---- shell, config, logging and the field query (srp_core.c) ----
const char* gs_steps_str(void);
const char* gs_steps_arrow(const char* arrow);
extern UINT g_helpVk;
extern UINT g_armVk;
extern UINT g_supVk;
extern UINT g_gsVk;
extern UINT g_warpVk;
extern UINT g_warpCancelVk;
extern UINT g_boVk;
extern UINT g_saveVk;
extern UINT g_camUnstickVk;
extern volatile int g_hkFocusOnly;
extern volatile int g_killMode;
extern volatile unsigned char g_battleOverlay;
extern int  g_logLevel;
void crash_report_install(void);
void crash_report_rearm(void);
extern int    g_gsStepN;
extern volatile int g_gsStep;
extern volatile unsigned char g_gsEnabled;
extern double g_gsFactor;
void gs_apply(int step);
extern volatile unsigned char g_armed;
extern int  g_dataDirOk;
int data_file(char* out, size_t n, const char* name);
void ff13log_reset(void);
void ff13loga(const char* fmt, ...);
void ff13log(const char* fmt, ...);
void ff13logv(const char* fmt, ...);
extern uintptr_t g_base;
int ui_english(void);
extern void* g_fontJp;
const char* ui_text(ovl_msg m);
int cfg_ieq(const char* a, const char* b);
int cfg_vk_bad(const UINT* vk);
const char* cfg_bad_list(void);
void config_load(void);
void state_save(void);
void state_load(void);
uint32_t field_zone_id(void);
int field_zone_state(void);
int wait_for_bytes(uintptr_t addr, const uint8_t* expect, int len, int timeoutMs);

// ---- one-hit cave, high speed and enemy suppression (srp_speed.c) ----
extern volatile int g_seenCount;
void __cdecl on_apply_hp_delta(uint32_t thisActor);
extern void* g_onehitCave;
void* install_onehit_cave(uintptr_t hookAddr, const volatile void* armedFlag, uintptr_t returnAddr);
extern const uint8_t P_SETATB[8];
extern volatile int   g_atbOk;
extern const uint8_t P_FRAMETICK[9];
void __cdecl on_frame_tick(uint32_t pDelta);
extern const uint8_t P_SETTER[6];
void __cdecl on_terr_setter(uint32_t id);
extern volatile unsigned char g_suppressEnabled;
int __cdecl should_skip_activate(void* ebpVal);
extern void* g_whCave;
void* install_withhide_cave(uintptr_t hookAddr, void* handler, uintptr_t contAddr, uintptr_t skipAddr);
void __cdecl on_probe_actArea (uint32_t ctx);
void __cdecl on_probe_withHide(uint32_t ctx);
void __cdecl on_probe_ignoreFA(uint32_t ctx);
void __cdecl on_probe_wait (uint32_t ctx);
void __cdecl on_probe_poll (uint32_t ctx);
void __cdecl on_probe_deact (uint32_t ctx);

// ---- battle swap, scene tables, arena/event doors and BGM (srp_battle.c) ----
extern const uint8_t P_SB[9];
extern char g_swapNameBuf[32];
extern volatile uint32_t g_swapBtscId;
extern volatile unsigned char g_swapEnabled;
extern volatile DWORD g_swapWindowUntil;
extern char g_zoneField[BGM_NAME_MAX + 1];
extern char g_bgmWant[BGM_NAME_MAX + 1];
extern volatile DWORD g_bgmWantUntil;
extern volatile unsigned char g_bgmDue;
extern char g_bgmTheirs[BGM_NAME_MAX + 1];
extern volatile int   g_bgmHoldMs;
extern volatile DWORD g_bgmHoldUntil;
extern volatile unsigned char g_bgmSkipHold;
extern char g_bgmHushed[BGM_NAME_MAX + 1];
extern volatile DWORD g_bgmWatchUntil;
extern char g_bgmWatchLast[BGM_NAME_MAX + 1];
int bgm_is_battle_track(const char* n);
int bgm_is_outcome_track(const char* n);
extern volatile uint32_t g_lastBtscId;
extern volatile uint32_t g_lastTouchedId;
extern volatile uint32_t g_fieldMgr;
void __cdecl on_start_battle(uint32_t vmctx);
extern const uint8_t P_ENC[6];
extern void* g_encCave;
uint32_t __cdecl on_encount_scene(uint32_t origId);
extern const uint8_t P_GBS[9];
extern const uint8_t P_ENCID[7];
extern const uint8_t P_SBTL[10];
extern const uint8_t P_LSND[6];
extern const uint8_t P_LCS[6];
extern char g_curCharset[CSET_NAME_MAX + 1];
extern char g_csLoaded[CSET_NAME_MAX + 1];
extern const char* volatile g_setupWant;
extern volatile DWORD g_setupUntil;
extern volatile DWORD g_gameTid;
void __cdecl on_load_charaset(uint32_t vmctx);
void vm_load_charaset(const char* name);
extern const uint8_t P_LCH[6];
extern volatile int g_lchOk;
extern const uint8_t P_ILC[6];
extern volatile int g_ilcOk;
extern volatile int g_looseLoaded;
void load_loose_specs(uint32_t btsc, const ff13_charaset* cs);
void loose_specs_report(void);
extern const uint8_t P_LBG[6];
extern char g_curBg[40];
extern volatile int g_bgAsked;
void __cdecl on_load_bg(uint32_t vmctx);
void vm_load_bg(const char* mapset);
void vm_load_sound(const char* name, const char* group);
void vm_field_ucon(void);
void vm_fade_in(void);
int menuskip_install(void);          // Window.showMainMenu made to return without opening
extern volatile unsigned char g_menuSkip;
void vm_restart_save(const char* rp);
extern volatile int   g_gateReplayVal;
extern volatile DWORD g_gateReplayUntil;
extern volatile int   g_uconDue;
void __cdecl on_drawenv_bg(uint32_t vmctx);
void __cdecl on_drawenv_chara(uint32_t vmctx);
void __cdecl on_box_on (uint32_t c);
void __cdecl on_box_off(uint32_t c);
void __cdecl on_layout_on (uint32_t c);
void __cdecl on_layout_off(uint32_t c);
void __cdecl on_screen_env(uint32_t vmctx);
int vm_get_work(int idx);
void vm_set_work(int idx, int val);
void vm_set_event_flag(const char* name, int on);
int vm_get_event_flag(const char* name);
void optima_log(const char* when);
void decks_apply(const signed char (*decks)[3], int n, int sel);
uint32_t party_state_key(void);
int party_battle_ids(int out[3]);
int decks_read_live(signed char out[][3], int maxn);
int deck_sel_live(void);
void vm_set_optima_deck(int deck);
int  vm_top_menu_get(void);
const char* zone_state_name(int st);
int scene_win_at_checkpoint(uint32_t btsc);
const signed char (*scene_decks(uint32_t btsc, int* n))[3];
extern const uint8_t P_OPTREG[6];
extern const uint8_t P_OPTSET[6];
extern const uint8_t P_OPTCLR[6];
extern const uint8_t P_OPTALL[3];
extern const uint8_t P_ADDROLE[6];
void __cdecl on_optima_regist(uint32_t vmctx);
void __cdecl on_optima_clear(uint32_t vmctx);
void __cdecl on_optima_clrall(uint32_t vmctx);
void __cdecl on_add_role(uint32_t vmctx);
void __cdecl on_optima_set(uint32_t vmctx);
extern const char* const* g_partyWho;
extern int g_partyWhoN;
extern int g_partyDoor;
const char* const* scene_party_who(uint32_t btsc, int* n);
void party_script_run(const char* when);
extern const struct ff13_arena_s* g_evPending;
extern volatile DWORD g_evAt;
extern volatile DWORD g_evGiveUpCap;
extern volatile DWORD g_evNoFightAt;
extern volatile int   g_evSkipDoor;
extern volatile uint32_t g_evTouch;
void vm_activate_area(const char* group);
void vm_party_marker(int group);
void vm_create_field_chara(const char* name, const char* model);
void vm_start_event(const char* name, const char* cb, const char* pack, const char* suc, const char* pack2, int script, const char* loadName, const char* loadPack);
void vm_dispose_event(const char* name, const char* pack, const char* pack2);
extern volatile int g_evCutSeen;
void __cdecl on_start_cinema(uint32_t vmctx);
void vm_sync_wait(void);
int leader_name(char out[20]);
int riding_chocobo(void);
extern volatile int g_ctlLocked;
void ctl_lock(void);
void ctl_hold(void);
// srp_proxy.c -- input silenced at the DirectInput proxy while a pick is being staged
void di_gate_arm(void);
int  di_gate_left_ms(void);
void di_gate_lift(void);
int  ctl_force_on(void);
void ctl_unlock(void);
void vm_start_battle(const char* arena, uint32_t flags, uint32_t btsc);
int chara_id_of(const char* nm);
extern volatile uint32_t g_apIdx[3];
extern volatile float    g_apSrc[3][3];
extern volatile uint32_t g_apObj[3];
extern volatile uintptr_t g_apRot[3];
extern volatile float    g_apPos[3][3];
extern volatile int      g_apCharId[3];
extern volatile float    g_apLeadD[3];
extern char              g_apName[3][24];
extern volatile int      g_apN;
extern volatile DWORD    g_apUntil;
extern volatile float    g_apRefX, g_apRefZ;
extern volatile int      g_apReady;
extern volatile int      g_apStage;
extern volatile int      g_apFace;
extern volatile int      g_apWp[3];
extern volatile int g_faceLogN;
extern unsigned char g_candFlags[WARP_MAXSLOT];
extern volatile int   g_placeBoss;
extern volatile uint32_t g_bossSlots[BOSS_SLOTS];
extern volatile int   g_bossSlotN;
extern volatile float g_bossSlotPos[BOSS_SLOTS][3];
extern volatile float g_bossX, g_bossY, g_bossZ;
extern volatile int   g_placeLogged;
extern volatile float g_bossOx, g_bossOy, g_bossOz;
extern volatile unsigned char g_enUsed[ARENA_ENEMIES];
extern volatile uint32_t g_bossObj;
extern volatile DWORD    g_bossProbeAt;
extern volatile DWORD g_bossOpenUntil;
extern const struct ff13_arena_s* g_arena;
extern const ff13_arena* g_arenaPending;
extern const signed char (*g_decksWant)[3];
extern volatile int      g_decksWantN;
extern volatile uint32_t g_decksWantFor;
extern volatile DWORD    g_decksAgainAt;
extern volatile uint32_t g_optimaWatch;
extern volatile DWORD    g_optimaWatchAt;
extern volatile int      g_optimaWatchN;
extern volatile DWORD    g_arenaStartAt;
extern volatile DWORD    g_arenaCamUntil;
extern volatile int      g_wsSeen;
extern volatile uint32_t g_camCtl;
extern volatile DWORD    g_camHoldUntil;
int arena_has_party(const struct ff13_arena_s* a);
const float* arena_party_stage(const struct ff13_arena_s* a, int i);
void arena_enemy_pick(const char* name, float* ox, float* oy, float* oz);
extern volatile int  g_lightSweep;
extern volatile int  g_sweepDone;
extern volatile int g_arenaCamera;
extern volatile DWORD g_lightMapAt;
extern volatile int   g_lightMapN;
int scene_light_apply(uint32_t btsc, int what, const char* when);
int scene_light_sweep(uint32_t btsc);
const ff13_arena* scene_arena(uint32_t btsc);
int scene_has_cutscene(uint32_t btsc);
extern volatile int g_stageLogged;
extern volatile float g_stagePrev[3];
extern volatile int   g_stagePrevHave;
int stage_origin(float* o);
extern const char* g_stageArena;
int stage_is_ours(const char* arena);
int stage_place(float ox, float oy, float oz, float* out);
extern const uint8_t P_ISREAD[6];
void __cdecl on_isread_call(uint32_t ecx);
extern const uint8_t P_CSREQ[7];
void __cdecl on_charaspec_request(uint32_t ecx, uint32_t retAddr, uint32_t* pA1, uint32_t* pA2);
extern const uint8_t P_ASECT[6];
void __cdecl on_actor_section(uint32_t actor);
int scene_resident(uint32_t btsc, const char** missing);
const ff13_scene_models* scene_models(uint32_t btsc);
int charaset_covers(const ff13_charaset* cs, const ff13_scene_models* sm);
int zone_has_charasets(uint32_t zone);
int band_listed_here(uint32_t zone, uint32_t band, uint32_t btsc);
int scene_belongs_here(uint32_t zone, uint32_t btsc);
const ff13_charaset* charaset_by_name(const char* name);
const ff13_charaset* charaset_needed(uint32_t zone, uint32_t btsc);
void __cdecl on_load_sound(uint32_t vmctx);
void __cdecl on_get_btsc(uint32_t ecx, uint32_t retAddr, uint32_t* pId, uint32_t* pFlag);
extern volatile uint32_t g_btlScene;
extern volatile int      g_btlCreated, g_btlFailed, g_btlNotLoaded;
extern volatile DWORD    g_btlStatAt, g_btlLogUntil;
extern volatile DWORD    g_bgmArmedAt;
extern volatile DWORD    g_btlLastMsgAt;
extern volatile int      g_btlShort;
extern volatile int      g_iwHitThisFight;
extern char g_btlBad[24];
extern volatile DWORD g_pickedEndAt;
void __cdecl on_battle_entry(uint32_t ecx, uint32_t retAddr, uint32_t* pId, uint32_t* pFlag);
extern const uint8_t P_GLOG[6];
void __cdecl on_game_log(uint32_t ecx, uint32_t fmtVal, uint32_t* pArgs, uint32_t* unused);
extern const uint8_t P_TRACE[5];
void __cdecl on_trace(uint32_t ecx, uint32_t fmtVal, uint32_t* pArgs, uint32_t* unused);
extern const uint8_t P_CAMSEQ[9];
void __cdecl on_cam_seq(uint32_t pName);
extern const uint8_t P_CAMREQ[9];
extern volatile int g_camSetOk;
int bm_state(void);
extern volatile DWORD g_camWatch;
extern volatile int   g_camDone;
void cam_disarm(void);
void __cdecl on_cam_request(uint32_t ecx, uint32_t retAddr, uint32_t* pReqSlot, uint32_t* unused);
extern volatile DWORD g_posSnap;
extern volatile DWORD g_camSnapAt;
extern volatile int   g_posN;
extern const uint8_t P_HASCAM[6];
void __cdecl on_has_cam(uint32_t ecx);
extern volatile int g_gatesDone;
void cam_pump(uint32_t btsc, DWORD now);
#ifdef FF13_DIAG
void bm_timeline(DWORD now);
#else
#define bm_timeline(now) ((void)0)
#endif
void __cdecl on_encount_check(uint32_t ecx);
extern volatile uint32_t g_encIdSeq;
extern volatile DWORD    g_touchAt;
extern volatile uint32_t g_touchSeq;
void __cdecl on_encount_id(uint32_t id);
extern const uint8_t P_BGM[9];
extern const uint8_t P_BGMLAZY[9];
int bgm_current(char* out /* BGM_NAME_MAX+1 */);
int bgm_lazy_play(const char* name);
void bgm_stop(const char* name, float fade);
extern char g_bgmFieldNow[BGM_NAME_MAX + 1];
extern char g_bgmMine[BGM_NAME_MAX + 1];
void bgm_zone_refresh(void);
const char* bgm_pick_track(uint32_t btsc, const char** origin);
void __cdecl on_bgm_play(uint32_t ecx, uint32_t retAddr, uint32_t* pName, uint32_t* unused);
void __cdecl on_bgm_lazyplay(uint32_t ecx, uint32_t retAddr, uint32_t* pName, uint32_t* pFade);
void* install_encscene_cave(uintptr_t hookAddr, void* handler);

// ---- battle picker, kill mode and the game-over path (srp_picker.c) ----
extern volatile uint32_t g_bsStarted;
void blackout_hold_on(void);
int blackout_on(void);
int is_boss_scene(uint32_t btsc);
void boss_learn(uint32_t btsc, const char* arena);
const char* bgm_event_track(uint32_t btsc);
const char* bgm_zone_track(uint32_t zone);
const ff13_btsc_info* btsc_info(uint32_t btsc);
void btsc_hand(uint32_t btsc, int mode, const unsigned short** jp, const char** en, unsigned* order, const unsigned short** tag, int* kind);
void zb_save(void);
void zb_load(void);
void zb_learn(uint32_t zone, uint32_t band, uint32_t touch);
extern volatile int      g_bsOpen;
extern volatile int      g_bsReq;
extern volatile int      g_bsRememberDue;
extern volatile int      g_bsCount;
extern volatile int      g_bsSel;
extern uint32_t          g_bsList[BS_MENU_MAX];
extern uint8_t           g_bsVar[BS_MENU_MAX];
extern UINT g_bsVk;
extern UINT g_bsUpVk;
extern UINT g_bsDownVk;
extern UINT g_bsLeftVk;
extern UINT g_bsRightVk;
void zb_remember_sel(uint32_t zone, uint32_t btsc, int mode);
extern const uint8_t P_SPECREPL[9];
extern const uint8_t P_ENCF4[7];
void preds_verify(void);
void __cdecl on_enc_field4(uint32_t ecx);
extern const uint8_t P_RESOLVETGT[9];
void __cdecl on_cond_target(uint32_t ecx, uint32_t kind, uint32_t* pActorId, uint32_t* pOut);
extern const uint8_t P_ABILLABEL[9];
void __cdecl on_ability_label(uint32_t ecx, uint32_t label);
extern const uint8_t P_AIAFTER[6];
// The condition dispatcher's join. Hooked so the enemy's own roll for the optional extra attack
// can be overruled -- see on_ai_cond and common/docs/ENEMY_AI_FLAGS_RE.md 3.9.
#define RVA_AICOND    0x158031       // VA 0x558031
extern const uint8_t P_AICOND[7];
void __cdecl on_ai_cond(uint32_t esp);
void extra_force_reset(void);
void extra_force_done(void);
#define RVA_AISTATE   0x149D40       // VA 0x549D40 -- the AI state setter
extern const uint8_t P_AISTATE[6];
void __cdecl on_ai_state(uint32_t ecx, uint32_t state, uint32_t* pRet, uint32_t* pUp);
void __cdecl on_ai_afterexec(uint32_t ctx);
void __cdecl on_spec_replace(uint32_t ecx, uint32_t name);
extern volatile int      g_homeHave;
extern volatile int      g_homeDue;
extern float g_homeX, g_homeY, g_homeZ;
#define HOME_CELLS_MAX 16
extern int g_homeCells[HOME_CELLS_MAX][2];
extern int g_homeCellsN;
int  save_capture_resident_cells(int out[][2], int maxn);
void save_mapset_census(const char* tag);
int  save_current_mapset(char out[17]);
void save_arm_reconcile(const int cells[][2], int n);
void save_arm_reconcile_sticky(const int cells[][2], int n, DWORD ms);
extern const uint8_t P_SENDTRIG[9];
extern volatile int   g_trigOk;
extern volatile int   g_workerHowOk;
extern volatile int g_goOk;
extern const uint8_t P_GOMENU[9];
extern const uint8_t P_GOSE[GO_SE_LEN];
extern volatile int g_goSeOk;
void __cdecl on_gameover_menu(uint32_t ctrl);
extern const uint8_t P_WORKHOW[5];
void __cdecl on_worker_how(uint32_t esp);
extern const uint8_t P_WORKIN[9];
extern const uint8_t P_WORKARM[5];
void __cdecl on_worker_in(uint32_t esp);
void __cdecl on_worker_arm(uint32_t esp);
extern const uint8_t P_PLACEJOIN[5];
extern volatile int g_bossGotMatrix;
void __cdecl on_place_join(uint32_t esp);
extern const uint8_t P_ITEMTAKE [6];
extern const uint8_t P_ITEMCOUNT[7];
extern const uint8_t P_ITEMGIVE [7];
extern const uint8_t P_TPGET[8];
extern const uint8_t P_TPSET[12];
extern const uint8_t P_LOCKENTER[9];
extern const uint8_t P_LOCKLEAVE[7];
extern volatile int   g_itemOk;
extern volatile int   g_tpOk;
void __cdecl on_item_take(uint32_t esp);
extern volatile int g_libraOk;
extern const uint8_t P_LOADSHOW[6];
extern const uint8_t P_LOADHIDE[10];
void __cdecl on_load_show(uint32_t mode);
void __cdecl on_load_hide(uint32_t ecx);
extern const uint8_t P_ENCREFUSE[5];
void __cdecl on_encount_refused(uint32_t ecx);
extern const uint8_t P_ACTIVATE[9];
extern const uint8_t P_ACTGATE[7];
extern volatile int g_iwArmed;
extern volatile int g_iwInstProbe, g_iwInstGate;
void __cdecl on_activate_probe(uint32_t esp);
void __cdecl on_activate_gate(uint32_t esp);
const char* kill_mode_name(int m);
const char* kill_mode_name_en(int m);
void kill_mode_apply(int mode, int announce);
void bs_pump(void);

// ---- warp cluster and the battle camera (srp_warp.c) ----
extern const uint8_t P_TP6[6];
void __cdecl on_getworldpos(uint32_t ecx);
extern volatile uint32_t g_warpActive;
extern volatile float g_ovrX, g_ovrY, g_ovrZ;
extern volatile float g_refX, g_refY, g_refZ;
extern volatile uint32_t g_leaderIdx;
extern volatile uint32_t g_warpMoved, g_warpSkip;
void __cdecl on_commit(uint32_t ecx, float* src);
int field_party_pos(float* x, float* y, float* z);
void arena_clear_flags(void);
extern const uint8_t P_CAMREC[6];
extern volatile int g_camRecOk;
void camera_follow_carry(float dx, float dy, float dz);
void camera_recentre_due(void);
void camera_follow_hold(void);
void field_camera_recenter(void);
extern const uint8_t P_WIDESHOT[8];
void __cdecl on_wide_shot(uint32_t esp);
extern const uint8_t P_GETCAM[6];
extern volatile int   g_getCamOk;
void battle_cam_watch(void);
void cam_control_dump(const char* when);
void arena_probe_formation(void);
void arena_recentre_reset(void);
void arena_hold(void);
void arena_collect(uint32_t ecx, uint32_t slot, const float* pos);
int warp_flag_cluster(float cx, float cy, float cz);
void hold_still_begin(void);
void hold_still_end(void);
extern volatile int   g_warpPrompt;
extern char           g_warpPromptMsg[288];
extern volatile DWORD g_warpPromptUntil;
void warp_load(void);
void warp_record(void);
void home_warp_back(void);
void warp_ask(void);
void warp_confirm(void);
void warp_cancel(void);

// ---- save anywhere (srp_save.c) ----
// These two live here but are written by config_load() in srp_core.c.
extern wchar_t g_listMark[9];
extern char g_saveDir[MAX_PATH];
void save_sidecars_load(void);
void save_install_hooks(void);
void save_poll_tick(DWORD now);

// ---- overlay services (srp_overlay.c) ----
extern volatile unsigned char g_helpOpen;
void flash_say_c(const char* s, DWORD col);
void flash_say(const char* s);
void vk_label(UINT b, char* out, size_t n);
int overlay_in_battle(void);
int read_via_ptr(unsigned ptrRva, int off);
void overlay_init(void);

#endif // SRP_INTERNAL_H
